import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/Header";
import { DM_Sans } from "next/font/google";

const font = DM_Sans({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "My Drawings",
  description: "Generated by create next app",
};
export const runtime = "edge";
export default function RootLayout({children,}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body className="bg-background container m-auto grid min-h-screen grid-rows-[auto,1fr,auto] ">
        <Header />
        {children}
        <footer className="text-center leading-[4rem] text-white bg-backgroundSecondary">
          <p
            className={`${font.className} text-base font-bold opacity-80 leading-[4rem] mx-8`}
          >
            © {new Date().getFullYear()} My drawings App
          </p>
        </footer>
      </body>
    </html>
  );
}
